#!/bin/bash
#SBATCH --partition=q16
#SBATCH --mem=60G
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --cpus-per-task=1

echo "========= Job started  at $(date) =========="
start=`date +%s`
source ./bin/activate # Activate virtual environ
python network_train.py $TEMP_PARAMS_FILE
rm $TEMP_PARAMS_FILE && echo "Removed: "$TEMP_PARAMS_FILE
echo "========= Job finished at $(date) =========="
end=`date +%s`
echo "Time: "$((end-start))"s"
