#!/bin/bash
#SBATCH --job-name=ForceCalc
#SBATCH --partition=q16
#SBATCH --mem=60G
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --ntasks-per-node=16
#SBATCH --cpus-per-task=1

#MAX_CHILD_MAX=25
#ulimit -u 2048
#export OMP_NUM_THREADS=16

echo "========= Job started  at $(date) =========="
start=`date +%s`
source ~/carbon_nn/bin/activate # Activate virtual environ

# python forces_save_test.py "../../logs/mixed_log/multi_perturb/features_few/Rc5/z-score/29-29-29_ba5pct/struc0.05/2018-06-06_10.13/" "test.npy" && echo "Saved test" &

# multi perturb 29-29-29
# for i in 0.001 0.005 0.01; do
#   python forces_save_test.py "../../logs/mixed_log/multi_perturb/features_few/Rc5/z-score/29-29-29_ba5pct/struc"$i"/2018-06-08_11.58/" "all_forces_test_multi_perturb-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_multi_perturb-29-29-29_struc"$i".npy" &
# done
# for i in $(seq -f %g 0.05 0.05 0.5); do
#   python forces_save_test.py "../../logs/mixed_log/multi_perturb/features_few/Rc5/z-score/29-29-29_ba5pct/struc"$i"/2018-06-06_10.13/" "all_forces_test_multi_perturb-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_multi_perturb-29-29-29_struc"$i".npy" &
# done
# for i in $(seq -f %g 0.55 0.05 1.0); do
#   python forces_save_test.py "../../logs/mixed_log/multi_perturb/features_few/Rc5/z-score/29-29-29_ba5pct/struc"$i"/2018-06-06_10.13/" "all_forces_test_multi_perturb-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_multi_perturb-29-29-29_struc"$i".npy" &
# done
# multi perturb 68-68
time_stamps=( "2018-06-08_00.07" "2018-06-08_00.08" "2018-06-08_00.08" "2018-06-08_00.10" "2018-06-08_00.12" "2018-06-08_00.15" "2018-06-08_00.15" "2018-06-08_00.16" "2018-06-08_00.18" "2018-06-08_00.20" "2018-06-08_00.23" "2018-06-08_00.24" "2018-06-08_00.24" "2018-06-08_00.30" "2018-06-08_00.32" "2018-06-08_00.33" "2018-06-08_00.33" "2018-06-08_00.35" "2018-06-08_00.35" )
j=0
# for i in $(seq -f %g 0.05 0.05 0.5); do
#   python forces_save_test.py "../../logs/mixed_log/multi_perturb/features_few/Rc5/z-score/68-68_ba5pct/struc"$i"/"${time_stamps[$j]}"/" "all_forces_test_multi_perturb-68-68_struc"$i".npy" && echo "Saved all_forces_test_multi_perturb-68-68_struc"$i".npy" &
#   j=$j+1
# done
j=10
# for i in $(seq -f %g 0.55 0.05 1.0); do
#   python forces_save_test.py "../../logs/mixed_log/multi_perturb/features_few/Rc5/z-score/68-68_ba5pct/struc"$i"/"${time_stamps[j]}"/" "all_forces_test_multi_perturb-68-68_struc"$i".npy" && echo "Saved all_forces_test_multi_perturb-68-68_struc"$i".npy" &
# 	j=$j+1
# done

# dual dual
interval=$()
# for i in 0.001 0.005 0.01 $(seq -f %g 0.05 0.05 0.25); do
# 	path=$(echo ../../logs/mixed_log/non_relaxed_double0.8_non_relaxed_double0.2/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-11_13.??/)
# 	echo $path
# 	python forces_save_test.py $path "all_forces_test_dual_dual-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_dual_dual-29-29-29_struc"$i".npy" &
# done
# for i in $(seq -f %g 0.30 0.05 0.60); do
# 	path=$(echo ../../logs/mixed_log/non_relaxed_double0.8_non_relaxed_double0.2/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-11_13.??/)
# 	echo $path
# 	python forces_save_test.py $path "all_forces_test_dual_dual-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_dual_dual-29-29-29_struc"$i".npy" &
# done
# for i in $(seq -f %g 0.65 0.05 1.0); do
# 	path=$(echo ../../logs/mixed_log/non_relaxed_double0.8_non_relaxed_double0.2/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-11_13.??/)
# 	echo $path
# 	python forces_save_test.py $path "all_forces_test_dual_dual-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_dual_dual-29-29-29_struc"$i".npy" &
# done

# dual relax
# for i in 0.001 0.005 0.01 $(seq -f %g 0.05 0.05 0.25); do
# 	path=$(echo ../../logs/mixed_log/non_relaxed_double0.8_relaxed0.2/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-11_13.??/)
# 	echo $path
# 	python forces_save_test.py $path "all_forces_test_dual_relax-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_dual_relax-29-29-29_struc"$i".npy" &
# done
# for i in $(seq -f %g 0.30 0.05 0.60); do
# 	path=$(echo ../../logs/mixed_log/non_relaxed_double0.8_relaxed0.2/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-11_13.??/)
# 	echo $path
# 	python forces_save_test.py $path "all_forces_test_dual_relax-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_dual_relax-29-29-29_struc"$i".npy" &
# done
# for i in $(seq -f %g 0.65 0.05 1.0); do
# 	path=$(echo ../../logs/mixed_log/non_relaxed_double0.8_relaxed0.2/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-11_13.??/)
# 	echo $path
# 	python forces_save_test.py $path "all_forces_test_dual_relax-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_dual_relax-29-29-29_struc"$i".npy" &
# done

# single single
# for i in 0.001 0.005 0.01 $(seq -f %g 0.05 0.05 0.25); do
# 	path=$(echo ../../logs/mixed_log/non_relaxed_single0.8_non_relaxed_single0.2/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-11_13.??/)
# 	echo $path
# 	python forces_save_test.py $path "all_forces_test_single_single-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_single_single-29-29-29_struc"$i".npy" &
# done
# for i in $(seq -f %g 0.30 0.05 0.60); do
# 	path=$(echo ../../logs/mixed_log/non_relaxed_single0.8_non_relaxed_single0.2/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-11_13.??/)
# 	echo $path
# 	python forces_save_test.py $path "all_forces_test_single_single-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_single_single-29-29-29_struc"$i".npy" &
# done
# for i in $(seq -f %g 0.65 0.05 1.0); do
# 	path=$(echo ../../logs/mixed_log/non_relaxed_single0.8_non_relaxed_single0.2/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-11_13.??/)
# 	echo $path
# 	python forces_save_test.py $path "all_forces_test_single_single-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_single_single-29-29-29_struc"$i".npy" &
# done

# single relax
# for i in 0.001 0.005 0.01 $(seq -f %g 0.05 0.05 0.25); do
# 	path=$(echo ../../logs/mixed_log/non_relaxed_single0.8_relaxed0.2/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-11_13.??/)
# 	echo $path
# 	python forces_save_test.py $path "all_forces_test_single_relax-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_single_relax-29-29-29_struc"$i".npy" &
# done
# for i in $(seq -f %g 0.30 0.05 0.60); do
# 	path=$(echo ../../logs/mixed_log/non_relaxed_single0.8_relaxed0.2/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-11_13.??/)
# 	echo $path
# 	python forces_save_test.py $path "all_forces_test_single_relax-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_single_relax-29-29-29_struc"$i".npy" &
# done
# for i in $(seq -f %g 0.65 0.05 1.0); do
# 	path=$(echo ../../logs/mixed_log/non_relaxed_single0.8_relaxed0.2/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-11_13.??/)
# 	echo $path
# 	python forces_save_test.py $path "all_forces_test_single_relax-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_single_relax-29-29-29_struc"$i".npy" &
# done

# relax-relax
for i in 0.001 0.005 0.01; do
	path=$(echo ../../logs/nn_logs/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-10_20.??/)
	echo $path
	python forces_save_test.py $path "all_forces_test_relax_relax-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_relax_relax-29-29-29_struc"$i".npy" &
done
# for i in $(seq -f %g 0.05 0.05 0.2); do
#   python forces_save_test.py "../../logs/nn_logs/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-10_20.31/" "all_forces_test_relax_relax-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_relax_relax-29-29-29_struc"$i".npy" &
# done
# for i in $(seq -f %g 0.25 0.05 0.75); do
#   python forces_save_test.py "../../logs/nn_logs/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-10_20.32/" "all_forces_test_relax_relax-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_relax_relax-29-29-29_struc"$i".npy" &
# done

# sleep 7200
# for i in $(seq -f %g 0.8 0.05 1.0); do
#   python forces_save_test.py "../../logs/nn_logs/features_few/Rc5/z-score/29-29-29_ba5pct_NEW/struc"$i"/2018-06-10_20.32/" "all_forces_test_relax_relax-29-29-29_struc"$i".npy" && echo "Saved all_forces_test_relax_relax-29-29-29_struc"$i".npy" &
# done

wait

echo "========= Job finished at $(date) =========="
end=`date +%s`
echo "Time: "$((end-start))"s"
